#!/bin/bash

LOG="/var/log/init-autossh-tunnel.log"

if [[ ! (-f $LOG) ]]; then
	touch $LOG
fi

echo `date` init-autossh-tunnel executed by $USER >> $LOG

sudo autossh -Nf -M 0 -q -o "ServerAliveInterval 60" -o "ServerAliveCountMax 3"  -R *:8000:localhost:80 root@federicogovoni.tk >> $LOG
sudo autossh -Nf -M 0 -q -o "ServerAliveInterval 60" -o "ServerAliveCountMax 3"  -R *:8011:192.168.0.11:81 root@federicogovoni.tk >> $LOG
sudo autossh -Nf -M 0 -q -o "ServerAliveInterval 60" -o "ServerAliveCountMax 3"  -R *:8012:192.168.0.12:81 root@federicogovoni.tk >> $LOG
sudo autossh -Nf -M 0 -q -o "ServerAliveInterval 60" -o "ServerAliveCountMax 3"  -R *:8013:192.168.0.13:81 root@federicogovoni.tk >> $LOG
sudo autossh -Nf -M 0 -q -o "ServerAliveInterval 60" -o "ServerAliveCountMax 3"  -R *:8022:localhost:22 root@federicogovoni.tk >> $LOG

