#!/bin/bash

CODE="1932"
ATTEMPTS="/home/fede/attempts"

GREEN=27
YELLOW=28
RED=29

STATUS=`sudo service zoneminder status | head -3 | tail -1 | cut -f2 -d'(' | cut -f1 -d')'`

echo $STATUS

if [[ $1 == $CODE ]]; then
	sudo rm $ATTEMPTS
	if [[ $STATUS == "dead" ]]; then
		sudo service zoneminder start
	else
		sudo service zoneminder stop
	fi
else
	sudo /home/fede/allarme/change_rasp_pin $GIALLO 1
	sleep 1
	sudo /home/fede/allarme/change_rasp_pin $GIALLO 0
	if [[ ! (-f $ATTEMPTS) ]]; then
		sudo touch $ATTEMPTS
		sudo chmod 666 $ATTEMPTS
		echo 1 > $ATTEMPTS
	else
		nr=`cat $ATTEMPTS`
		nr=`expr $nr + 1`
		echo $nr > $ATTEMPTS
		if [[ $nr -ge 3 ]]; then
			sudo /home/fede/allarme/azioni_allarme
		fi
	fi
fi
